name: Feature request
description: Suggest an idea
type: Feature
body:
  - type: dropdown
    id: request-type
    attributes:
      label: Request type
      description: Helps with triage.
      options:
        - General feature
        - Compatibility
        - Quality of life
        - Balance
        - Performance / optimization
      default: 0

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: Describe the problem and why it matters. If this is a compatibility request, name the other mod(s).

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: What should happen? Describe the desired behavior. For compatibility requests, also add the appropriate label.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives you've considered
      description: List alternative solutions or features you've thought about and why they're not ideal.

  - type: textarea
    id: upstream
    attributes:
      label: Upstream status (original mod)
      description: If applicable, link to the upstream issue/PR and note the outcome. If this is a compatibility request for another mod, you can skip this.

  - type: checkboxes
    id: impact
    attributes:
      label: Impact & considerations
      description: Check any that apply, then add details below if needed.
      options:
        - label: Performance implications
        - label: Balance concerns
        - label: Needs a config option
        - label: Save/world compatibility impact
        - label: Migration required

  - type: textarea
    id: impact-notes
    attributes:
      label: Impact details (optional)
      description: Performance notes, balance considerations, config options, save/world compatibility, or migration notes.

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Any other context, screenshots, mockups, references, or links.
