name: Vulnerability report
description: Security-impacting bug report.
type: Bug
labels: vulnerability
body:
  - type: markdown
    attributes:
      value: |
        **Responsible disclosure:** For critical issues (RCE, priv-esc, data exfil), join our Discord and DM the devs instead of a public issue.

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: One-paragraph description + security impact.
      placeholder: "e.g., Non-OP can execute server commands via packet X"
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - Critical
        - High
        - Medium
        - Low
        - Informational
    validations:
      required: true

  - type: dropdown
    id: surface
    attributes:
      label: Attack surface
      options:
        - Server-side
        - Client-side
        - Both
        - Network/protocol
    validations:
      required: true

  - type: dropdown
    id: privs
    attributes:
      label: Privileges required
      options:
        - None (unauthenticated/any player)
        - Player
        - OP/admin
        - Filesystem/RCON
        - Local/physical
    validations:
      required: true

  - type: checkboxes
    id: context
    attributes:
      label: Context
      options:
        - label: Singleplayer
        - label: Integrated server (LAN)
        - label: Multiplayer (dedicated)

  - type: textarea
    id: poc
    attributes:
      label: PoC / Repro
      description: Minimal steps or script to trigger the issue (sanitize secrets).
    validations:
      required: true

  - type: checkboxes
    id: confirmed-latest
    attributes:
      label: Confirmation
      options:
        - label: Reproduced on the latest successful GitHub Actions build
          required: true

  - type: textarea
    id: env
    attributes:
      label: Environment
      placeholder: "OS, Java, Forge, server type; other mods involved (if any); relevant config toggles"

  - type: textarea
    id: evidence
    attributes:
      label: Evidence
      description: Links to logs (e.g., https://mclo.gs/), screenshots, short videos.

  - type: textarea
    id: mitigations
    attributes:
      label: Temporary mitigations
      placeholder: "Disable feature X; block packet Y; config Z=false"
